// ===== QUICK NOTES =====
let noteSaveTimer = null;
let noteSaveRevision = 0;
let selectedNoteType = 'note';
let selectedHomeMemoryScope = 'match';
let quickNoteMemories = [];
let quickNoteDrafts = createDefaultQuickNoteDrafts();
let quickNoteScheduleDrafts = createDefaultQuickNoteScheduleDrafts();

function createDefaultQuickNoteDrafts() { return { note: '', reminder: '', checklist: '', plan: '' }; }
function createDefaultQuickNoteScheduleDrafts() { return { reminder: { due: '', time: '', advanceValue: 10, advanceUnit: 'minutes' }, plan: { due: '', time: '', advanceValue: 10, advanceUnit: 'minutes' } }; }
function mergeQuickNoteDrafts(drafts, fallback = '') { return { ...createDefaultQuickNoteDrafts(), note: fallback, ...(drafts || {}) }; }
function mergeQuickNoteScheduleDrafts(drafts) { return { ...createDefaultQuickNoteScheduleDrafts(), ...(drafts || {}) }; }
function shouldShowSchedule(type = selectedNoteType) { return type === 'reminder' || type === 'plan'; }
function getSelectedScheduleDraft(type = selectedNoteType) { return quickNoteScheduleDrafts[type] || createDefaultQuickNoteScheduleDrafts().reminder; }
function normalizeMemoryText(type, text) { const value = String(text || '').trim(); return type === 'checklist' ? value.split('\n').map((line) => line.trim()).filter(Boolean).join('\n') : value; }
function getChecklistItems(text) { return String(text || '').split('\n').map((line) => line.replace(/^[-*]\s*/, '').trim()).filter(Boolean); }
function hasQuickNoteDraftContent(type = selectedNoteType) { return Boolean(String(quickNoteDrafts[type] || '').trim()); }
function syncQuickNoteDraftFromComposer() { const noteEl = document.getElementById('quick-note'); if (!noteEl) return; quickNoteDrafts[selectedNoteType] = noteEl.value; if (shouldShowSchedule()) quickNoteScheduleDrafts[selectedNoteType] = { due: document.getElementById('note-due-input')?.value || '', time: document.getElementById('note-time-input')?.value || '', advanceValue: Number(document.getElementById('note-advance-input')?.value || 10), advanceUnit: document.getElementById('note-advance-unit')?.value || 'minutes' }; }
function updateNoteSaveUI(state) { const badge = document.getElementById('note-save-state'); if (!badge) return; const copy = getNewTabCopy(); const labels = { idle: copy.saved || 'Saved', draft: copy.draft || 'Draft', saving: copy.saving || 'Saving', saved: copy.saved || 'Saved' }; badge.textContent = labels[state] || labels.idle; badge.className = `note-save-state is-${state || 'idle'}`; }
function updateNoteContentState() { const stateEl = document.getElementById('note-content-state'); if (stateEl) stateEl.textContent = hasQuickNoteDraftContent() ? 'Draft ready' : (getNewTabCopy().noContent || 'No content'); }
function applyQuickNoteTypeUI() { document.querySelectorAll('.note-type-pill').forEach((button) => button.classList.toggle('active', button.dataset.type === selectedNoteType)); document.getElementById('quick-note')?.classList.toggle('is-checklist-mode', selectedNoteType === 'checklist'); const show = shouldShowSchedule(); if (document.getElementById('note-schedule-row')) document.getElementById('note-schedule-row').hidden = !show; if (document.getElementById('note-advance-row')) document.getElementById('note-advance-row').hidden = !show; }
function hydrateQuickNoteComposer() { const noteEl = document.getElementById('quick-note'); if (!noteEl) return; noteEl.value = quickNoteDrafts[selectedNoteType] || ''; const schedule = getSelectedScheduleDraft(); ['due','time'].forEach(() => {}); if (document.getElementById('note-due-input')) document.getElementById('note-due-input').value = schedule.due || ''; if (document.getElementById('note-time-input')) document.getElementById('note-time-input').value = schedule.time || ''; if (document.getElementById('note-advance-input')) document.getElementById('note-advance-input').value = schedule.advanceValue || 10; if (document.getElementById('note-advance-unit')) document.getElementById('note-advance-unit').value = schedule.advanceUnit || 'minutes'; applyQuickNoteTypeUI(); updateNoteContentState(); }
async function persistQuickNoteDrafts(revision = noteSaveRevision) { await store.set({ quick_note_drafts: quickNoteDrafts, quick_note_due_drafts: quickNoteScheduleDrafts }); if (revision === noteSaveRevision) updateNoteSaveUI(hasQuickNoteDraftContent() ? 'draft' : 'saved'); }
function queueQuickNoteDraftSave() { syncQuickNoteDraftFromComposer(); updateNoteContentState(); updateNoteSaveUI('saving'); const revision = ++noteSaveRevision; clearTimeout(noteSaveTimer); noteSaveTimer = setTimeout(() => persistQuickNoteDrafts(revision), 250); }
function renderHomeMemoryBody(memory) { if (memory.type === 'checklist') return '<ul class="home-memory-checklist">' + getChecklistItems(memory.text).slice(0, 3).map((item) => `<li class="home-memory-checklist-item"><span class="home-memory-checklist-box"></span><span class="home-memory-checklist-label">${escHtml(item)}</span></li>`).join('') + '</ul>'; return `<div class="home-memory-text">${escHtml(memory.text || '')}</div>`; }
function renderHomeMemories(memories = quickNoteMemories) { const list = document.getElementById('home-memory-list'); const count = document.getElementById('home-memory-list-count'); if (!list) return; const active = (memories || []).filter((memory) => memory && !memory.deleted); const visible = active.filter((memory) => selectedHomeMemoryScope === 'all' || selectedHomeMemoryScope === 'recent' || memory.type === selectedNoteType).slice(0, 2); if (count) count.textContent = String(visible.length); list.innerHTML = visible.length ? visible.map((memory) => `<article class="home-memory-item"><div class="home-memory-meta"><span class="home-memory-type">${escHtml(getQuickNoteTypeMeta(memory.type || 'note').label)}</span></div>${renderHomeMemoryBody(memory)}</article>`).join('') : `<div class="home-memory-empty">${escHtml(getNewTabCopy().memoryEmpty || 'No saved notes yet')}</div>`; }
function renderNoteHintChip() {}
async function loadQuickNote() { const data = await store.get(['quick_note_drafts', 'quick_note_due_drafts', 'memories']); quickNoteDrafts = mergeQuickNoteDrafts(data.quick_note_drafts || {}); quickNoteScheduleDrafts = mergeQuickNoteScheduleDrafts(data.quick_note_due_drafts || {}); quickNoteMemories = Array.isArray(data.memories) ? data.memories : []; hydrateQuickNoteComposer(); renderHomeMemories(); updateNoteSaveUI(hasQuickNoteDraftContent() ? 'draft' : 'saved'); }
async function saveQuickNoteToMemories() { syncQuickNoteDraftFromComposer(); const text = normalizeMemoryText(selectedNoteType, quickNoteDrafts[selectedNoteType]); if (!text) return; const memory = { id: Date.now().toString(), type: selectedNoteType, text, created: Date.now(), updated: Date.now(), deleted: false, ...(shouldShowSchedule() ? getSelectedScheduleDraft() : {}) }; const data = await store.get(['memories']); const memories = Array.isArray(data.memories) ? data.memories : []; memories.unshift(memory); quickNoteDrafts[selectedNoteType] = ''; await store.set({ memories, quick_note_drafts: quickNoteDrafts, quick_note_due_drafts: quickNoteScheduleDrafts }); quickNoteMemories = memories; hydrateQuickNoteComposer(); renderHomeMemories(); updateNoteSaveUI('saved'); }

document.getElementById('quick-note')?.addEventListener('input', queueQuickNoteDraftSave);
['note-due-input', 'note-time-input', 'note-advance-input', 'note-advance-unit'].forEach((id) => { document.getElementById(id)?.addEventListener('input', queueQuickNoteDraftSave); document.getElementById(id)?.addEventListener('change', queueQuickNoteDraftSave); });
document.getElementById('note-save-btn')?.addEventListener('click', saveQuickNoteToMemories);
document.getElementById('note-type-row')?.addEventListener('click', (e) => { const button = e.target.closest('.note-type-pill[data-type]'); if (!button) return; syncQuickNoteDraftFromComposer(); selectedNoteType = button.dataset.type; hydrateQuickNoteComposer(); });
document.getElementById('home-memory-scope-switch')?.addEventListener('click', (e) => { const button = e.target.closest('.home-memory-scope-btn[data-scope]'); if (!button) return; selectedHomeMemoryScope = button.dataset.scope; document.querySelectorAll('.home-memory-scope-btn').forEach((node) => node.classList.toggle('active', node === button)); renderHomeMemories(); });
document.getElementById('note-open-memory')?.addEventListener('click', (e) => { e.preventDefault(); openOffiqaSidebar('memory-personal', { memoryFilter: selectedNoteType }); });
document.getElementById('task-open-sidebar')?.addEventListener('click', (e) => { e.preventDefault(); openOffiqaSidebar('focus-today'); });
document.getElementById('meeting-open-sidebar')?.addEventListener('click', (e) => { e.preventDefault(); openOffiqaSidebar('meetings-sidebar'); });
document.getElementById('session-open-sidebar')?.addEventListener('click', (e) => { e.preventDefault(); openOffiqaSidebar('sessions-sidebar'); });

window.offiqaNewtabFeatureInitializers = window.offiqaNewtabFeatureInitializers || {};
window.offiqaNewtabFeatureInitializers.quickNotes = async () => { await loadQuickNote(); };
